<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $units = [
            // Roman Units
            [
                'name' => 'Legionnaire',
                'key' => 'legionnaire',
                'tribe' => 'roman',
                'description' => 'Roman infantry unit',
                'attack' => 40,
                'defense_infantry' => 35,
                'defense_cavalry' => 50,
                'speed' => 6,
                'carry_capacity' => 50,
                'costs' => json_encode(['wood' => 120, 'clay' => 100, 'iron' => 150, 'crop' => 30]),
                'requirements' => json_encode(['barracks' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Praetorian',
                'key' => 'praetorian',
                'tribe' => 'roman',
                'description' => 'Roman defensive unit',
                'attack' => 30,
                'defense_infantry' => 65,
                'defense_cavalry' => 35,
                'speed' => 5,
                'carry_capacity' => 20,
                'costs' => json_encode(['wood' => 100, 'clay' => 130, 'iron' => 160, 'crop' => 70]),
                'requirements' => json_encode(['barracks' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Imperian',
                'key' => 'imperian',
                'tribe' => 'roman',
                'description' => 'Roman cavalry unit',
                'attack' => 70,
                'defense_infantry' => 40,
                'defense_cavalry' => 25,
                'speed' => 16,
                'carry_capacity' => 50,
                'costs' => json_encode(['wood' => 150, 'clay' => 160, 'iron' => 210, 'crop' => 80]),
                'requirements' => json_encode(['barracks' => 5, 'stable' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Equites Legati',
                'key' => 'equites_legati',
                'tribe' => 'roman',
                'description' => 'Roman scout unit',
                'attack' => 0,
                'defense_infantry' => 20,
                'defense_cavalry' => 10,
                'speed' => 16,
                'carry_capacity' => 0,
                'costs' => json_encode(['wood' => 140, 'clay' => 160, 'iron' => 20, 'crop' => 40]),
                'requirements' => json_encode(['barracks' => 5, 'stable' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Equites Imperatoris',
                'key' => 'equites_imperatoris',
                'tribe' => 'roman',
                'description' => 'Roman heavy cavalry',
                'attack' => 120,
                'defense_infantry' => 65,
                'defense_cavalry' => 50,
                'speed' => 14,
                'carry_capacity' => 100,
                'costs' => json_encode(['wood' => 550, 'clay' => 640, 'iron' => 800, 'crop' => 180]),
                'requirements' => json_encode(['barracks' => 10, 'stable' => 5]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Equites Caesaris',
                'key' => 'equites_caesaris',
                'tribe' => 'roman',
                'description' => 'Roman elite cavalry',
                'attack' => 180,
                'defense_infantry' => 80,
                'defense_cavalry' => 105,
                'speed' => 10,
                'carry_capacity' => 70,
                'costs' => json_encode(['wood' => 550, 'clay' => 640, 'iron' => 800, 'crop' => 180]),
                'requirements' => json_encode(['barracks' => 10, 'stable' => 5]),
                'is_special' => false,
                'is_active' => true,
            ],
            // Teuton Units
            [
                'name' => 'Clubswinger',
                'key' => 'clubswinger',
                'tribe' => 'teuton',
                'description' => 'Teuton infantry unit',
                'attack' => 40,
                'defense_infantry' => 20,
                'defense_cavalry' => 5,
                'speed' => 7,
                'carry_capacity' => 60,
                'costs' => json_encode(['wood' => 95, 'clay' => 75, 'iron' => 40, 'crop' => 40]),
                'requirements' => json_encode(['barracks' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Spearman',
                'key' => 'spearman',
                'tribe' => 'teuton',
                'description' => 'Teuton defensive unit',
                'attack' => 10,
                'defense_infantry' => 35,
                'defense_cavalry' => 60,
                'speed' => 7,
                'carry_capacity' => 40,
                'costs' => json_encode(['wood' => 145, 'clay' => 70, 'iron' => 85, 'crop' => 40]),
                'requirements' => json_encode(['barracks' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Axeman',
                'key' => 'axeman',
                'tribe' => 'teuton',
                'description' => 'Teuton cavalry unit',
                'attack' => 60,
                'defense_infantry' => 30,
                'defense_cavalry' => 30,
                'speed' => 6,
                'carry_capacity' => 40,
                'costs' => json_encode(['wood' => 130, 'clay' => 75, 'iron' => 40, 'crop' => 60]),
                'requirements' => json_encode(['barracks' => 3, 'stable' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Scout',
                'key' => 'scout',
                'tribe' => 'teuton',
                'description' => 'Teuton scout unit',
                'attack' => 0,
                'defense_infantry' => 10,
                'defense_cavalry' => 5,
                'speed' => 9,
                'carry_capacity' => 0,
                'costs' => json_encode(['wood' => 160, 'clay' => 100, 'iron' => 50, 'crop' => 50]),
                'requirements' => json_encode(['barracks' => 1, 'stable' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Paladin',
                'key' => 'paladin',
                'tribe' => 'teuton',
                'description' => 'Teuton heavy cavalry',
                'attack' => 55,
                'defense_infantry' => 100,
                'defense_cavalry' => 40,
                'speed' => 10,
                'carry_capacity' => 110,
                'costs' => json_encode(['wood' => 370, 'clay' => 270, 'iron' => 290, 'crop' => 75]),
                'requirements' => json_encode(['barracks' => 5, 'stable' => 3]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Teutonic Knight',
                'key' => 'teutonic_knight',
                'tribe' => 'teuton',
                'description' => 'Teuton elite cavalry',
                'attack' => 150,
                'defense_infantry' => 50,
                'defense_cavalry' => 75,
                'speed' => 9,
                'carry_capacity' => 80,
                'costs' => json_encode(['wood' => 450, 'clay' => 515, 'iron' => 480, 'crop' => 80]),
                'requirements' => json_encode(['barracks' => 10, 'stable' => 5]),
                'is_special' => false,
                'is_active' => true,
            ],
            // Gaul Units
            [
                'name' => 'Phalanx',
                'key' => 'phalanx',
                'tribe' => 'gaul',
                'description' => 'Gaul infantry unit',
                'attack' => 15,
                'defense_infantry' => 40,
                'defense_cavalry' => 50,
                'speed' => 7,
                'carry_capacity' => 35,
                'costs' => json_encode(['wood' => 100, 'clay' => 130, 'iron' => 55, 'crop' => 30]),
                'requirements' => json_encode(['barracks' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Swordsman',
                'key' => 'swordsman',
                'tribe' => 'gaul',
                'description' => 'Gaul defensive unit',
                'attack' => 65,
                'defense_infantry' => 35,
                'defense_cavalry' => 20,
                'speed' => 6,
                'carry_capacity' => 45,
                'costs' => json_encode(['wood' => 140, 'clay' => 150, 'iron' => 185, 'crop' => 60]),
                'requirements' => json_encode(['barracks' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Pathfinder',
                'key' => 'pathfinder',
                'tribe' => 'gaul',
                'description' => 'Gaul cavalry unit',
                'attack' => 0,
                'defense_infantry' => 20,
                'defense_cavalry' => 10,
                'speed' => 17,
                'carry_capacity' => 0,
                'costs' => json_encode(['wood' => 170, 'clay' => 150, 'iron' => 20, 'crop' => 40]),
                'requirements' => json_encode(['barracks' => 5, 'stable' => 1]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Theutates Thunder',
                'key' => 'theutates_thunder',
                'tribe' => 'gaul',
                'description' => 'Gaul heavy cavalry',
                'attack' => 90,
                'defense_infantry' => 25,
                'defense_cavalry' => 40,
                'speed' => 19,
                'carry_capacity' => 75,
                'costs' => json_encode(['wood' => 350, 'clay' => 450, 'iron' => 230, 'crop' => 60]),
                'requirements' => json_encode(['barracks' => 5, 'stable' => 3]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Druidrider',
                'key' => 'druidrider',
                'tribe' => 'gaul',
                'description' => 'Gaul elite cavalry',
                'attack' => 45,
                'defense_infantry' => 115,
                'defense_cavalry' => 55,
                'speed' => 16,
                'carry_capacity' => 35,
                'costs' => json_encode(['wood' => 360, 'clay' => 330, 'iron' => 280, 'crop' => 120]),
                'requirements' => json_encode(['barracks' => 10, 'stable' => 5]),
                'is_special' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Haeduan',
                'key' => 'haeduan',
                'tribe' => 'gaul',
                'description' => 'Gaul elite cavalry',
                'attack' => 140,
                'defense_infantry' => 60,
                'defense_cavalry' => 165,
                'speed' => 16,
                'carry_capacity' => 65,
                'costs' => json_encode(['wood' => 500, 'clay' => 620, 'iron' => 675, 'crop' => 170]),
                'requirements' => json_encode(['barracks' => 10, 'stable' => 5]),
                'is_special' => false,
                'is_active' => true,
            ],
        ];

        foreach ($units as $unit) {
            \App\Models\Game\UnitType::firstOrCreate(
                ['key' => $unit['key'], 'tribe' => $unit['tribe']],
                $unit
            );
        }
    }
}
