<?php
namespace Database\Seeders\Tables\database\seeders\Tables\UsersTestSeeder.php;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --tables=users --output=database/seeders/Tables/UsersTestSeeder.php
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'name' => 'Test Audit Update - 1758933575',
                'email' => 'admin@example.com',
                'email_verified_at' => '2025-09-25 23:37:48',
                'password' => '$2y$12$rvcg4bExpSqOD6neaG.b7.He81/Tes9wWOkWFdIPJ1qvvBmQpOg26',
                'remember_token' => 'IYmHMwbtYw6bKfrJ8eouUE33Sh5vHMZ2qSslBhO65JCDvxcLrhPJp9ri7VPl',
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-27 00:39:35',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 2,
                'name' => 'Darion Cruickshank',
                'email' => 'grimes.oren@example.com',
                'email_verified_at' => '2025-09-25 23:37:48',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'WYFIasYHxD',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 3,
                'name' => 'Gail Bogisich',
                'email' => 'vhudson@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'mb9u14DHTY',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 4,
                'name' => 'Mrs. Bridgette Swaniawski IV',
                'email' => 'mann.meda@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'w7RjQwKxPM',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 5,
                'name' => 'Gerard Wintheiser',
                'email' => 'aboyer@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'b7rHHqsgQe',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 6,
                'name' => 'Susana Hoppe',
                'email' => 'nrenner@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'bBZDDGMY27',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 7,
                'name' => 'Carol Bayer MD',
                'email' => 'peffertz@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'Dvan2H27dA',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 8,
                'name' => 'Ms. Ada Russel Jr.',
                'email' => 'bergnaum.lavern@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'nuhzd0Sebp',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 9,
                'name' => 'Dr. Johnathan Herzog I',
                'email' => 'melyssa.lebsack@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'X7QqMkc78b',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 10,
                'name' => 'Ariane Gerhold Sr.',
                'email' => 'bcormier@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'hEbfChUYvr',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 11,
                'name' => 'Brycen Williamson',
                'email' => 'gottlieb.cedrick@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'RMoDCAiWnT',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 12,
                'name' => 'Anabelle Jacobs',
                'email' => 'isai.braun@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'b2w7FUZmBx',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 13,
                'name' => 'Eva Greenfelder',
                'email' => 'olga.feest@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'l6QwKlLGjB',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 14,
                'name' => 'Alejandra Dach',
                'email' => 'runte.jazmin@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'GV1x6wqcop',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 15,
                'name' => 'Eldon Hackett',
                'email' => 'stracke.carmine@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '9CaFEBpXYn',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 16,
                'name' => 'Junior Harber',
                'email' => 'orodriguez@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'DtsIteotJW',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 17,
                'name' => 'Emil Crona',
                'email' => 'mhaag@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'FIEgimQjnm',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 18,
                'name' => 'Torey Swaniawski V',
                'email' => 'ebert.lamont@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'PHZx9vzQp4',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 19,
                'name' => 'Mr. Torey Spencer',
                'email' => 'rwolff@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'edANFekznD',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 20,
                'name' => 'Wilfred Wilderman',
                'email' => 'ybalistreri@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'dMYkTcc0FD',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 21,
                'name' => 'Breana Cummerata Sr.',
                'email' => 'simonis.florida@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'zxJSykGORW',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 22,
                'name' => 'Mariana Harvey IV',
                'email' => 'lorenzo02@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '8tsV6JMvPg',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 23,
                'name' => 'Mrs. Berenice Gislason Sr.',
                'email' => 'danielle31@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'XnhW39Mt8g',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 24,
                'name' => 'Dante Eichmann III',
                'email' => 'robert74@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '0WT65IRl73',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 25,
                'name' => 'Kaleigh Stokes II',
                'email' => 'oma.beer@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '3Wro9Lvipy',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 26,
                'name' => 'Rubye Krajcik Jr.',
                'email' => 'babbott@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '9FvFIfnhFg',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 27,
                'name' => 'Bruce Bergstrom',
                'email' => 'zharvey@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'IOWDUfT7BZ',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 28,
                'name' => 'Milo Flatley',
                'email' => 'heaney.jesse@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'W8Wf46YIbB',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 29,
                'name' => 'Danielle O\'Reilly',
                'email' => 'beahan.nicholas@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'VnLi4z7kLQ',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 30,
                'name' => 'Melyssa Schmidt Jr.',
                'email' => 'etha33@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'fVk3M5ulJ7',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 31,
                'name' => 'Joesph Stehr III',
                'email' => 'karli.medhurst@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'yDZDymXPsr',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 32,
                'name' => 'Stephon Anderson',
                'email' => 'travon61@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'pyxMrwTsgP',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 33,
                'name' => 'Prof. Hyman Satterfield II',
                'email' => 'chesley.murazik@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'o8SeQQQP2R',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 34,
                'name' => 'Henry Renner',
                'email' => 'dickens.dustin@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'PsIegWvE96',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 35,
                'name' => 'Zane Hintz',
                'email' => 'herzog.jerel@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'BMH0dlGMyx',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 36,
                'name' => 'Mr. Gilbert Konopelski',
                'email' => 'ybechtelar@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'Z2JcHmmeqf',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 37,
                'name' => 'Mrs. Hannah Lubowitz',
                'email' => 'qjakubowski@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'ttsolbdvXN',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 38,
                'name' => 'Mr. Grayce Dibbert MD',
                'email' => 'kub.kylee@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'gvLDRG9OtP',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 39,
                'name' => 'Mr. Cole Fahey',
                'email' => 'critchie@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'orVB2h7GTU',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 40,
                'name' => 'Talia Yost',
                'email' => 'jovani.schamberger@example.com',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'Uqueg7d4vf',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 41,
                'name' => 'Carmella Blick',
                'email' => 'karianne49@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '8uDTglc3NC',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 42,
                'name' => 'Nathanial Veum',
                'email' => 'summer.rice@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'LtrzAaUjv5',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 43,
                'name' => 'Ross O\'Conner',
                'email' => 'thurman.jacobs@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'hFrwqTOuF9',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 44,
                'name' => 'Dr. Santos Dicki III',
                'email' => 'cbosco@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'AtFkO29jKf',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 45,
                'name' => 'Harmon Marks',
                'email' => 'elody41@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'R6rcLV2GTs',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 46,
                'name' => 'Zackary Feest IV',
                'email' => 'ellis.hilpert@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'rOoLYPofNC',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 47,
                'name' => 'Dr. Jany Rohan V',
                'email' => 'koelpin.makenzie@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'bFxOqBg64w',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 48,
                'name' => 'Aglae Beier I',
                'email' => 'jade.kertzmann@example.org',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'ZBRVHRplP3',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 49,
                'name' => 'Dr. Robin Bartell II',
                'email' => 'smitham.earnestine@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => '5jvq8QKAsp',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 50,
                'name' => 'Braeden Glover Jr.',
                'email' => 'marlee.smitham@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'i9ugq6r9YE',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 51,
                'name' => 'Shany Roob',
                'email' => 'danyka.buckridge@example.net',
                'email_verified_at' => '2025-09-25 23:37:49',
                'password' => '$2y$12$nDhI/aw15IBj0xPt3/4o2.SHqkyTHuIOmBgiY5.ShV5k1n7.Frnzq',
                'remember_token' => 'tQumt3uvhX',
                'created_at' => '2025-09-25 23:37:49',
                'updated_at' => '2025-09-25 23:37:49',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 53,
                'name' => 'Mr. Torrance Abshire DDS',
                'email' => 'pinkie32@example.org',
                'email_verified_at' => '2025-09-27 00:41:34',
                'password' => '$2y$12$uX21Y9BUAVkr1ZCszrvegOeORey2GgVKrplkptTLWaGtpeeSpiYWS',
                'remember_token' => 'QsFed5hqaV',
                'created_at' => '2025-09-27 00:41:35',
                'updated_at' => '2025-09-27 00:41:35',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 54,
                'name' => 'Lula Donnelly PhD',
                'email' => 'christian.kemmer@example.com',
                'email_verified_at' => '2025-09-27 00:41:35',
                'password' => '$2y$12$uX21Y9BUAVkr1ZCszrvegOeORey2GgVKrplkptTLWaGtpeeSpiYWS',
                'remember_token' => 'Dku7bGItZN',
                'created_at' => '2025-09-27 00:41:35',
                'updated_at' => '2025-09-27 00:41:35',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 55,
                'name' => 'Rashawn Witting',
                'email' => 'wolf.nicholaus@example.com',
                'email_verified_at' => '2025-09-27 00:41:35',
                'password' => '$2y$12$uX21Y9BUAVkr1ZCszrvegOeORey2GgVKrplkptTLWaGtpeeSpiYWS',
                'remember_token' => '9sVSE3xsZs',
                'created_at' => '2025-09-27 00:41:35',
                'updated_at' => '2025-09-27 00:41:35',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 56,
                'name' => 'Prof. Madelynn Leffler',
                'email' => 'candace.rath@example.net',
                'email_verified_at' => '2025-09-27 00:41:35',
                'password' => '$2y$12$uX21Y9BUAVkr1ZCszrvegOeORey2GgVKrplkptTLWaGtpeeSpiYWS',
                'remember_token' => 'ciFx2QdpXz',
                'created_at' => '2025-09-27 00:41:35',
                'updated_at' => '2025-09-27 00:41:35',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 57,
                'name' => 'Maci Donnelly',
                'email' => 'morissette.queenie@example.net',
                'email_verified_at' => '2025-09-27 00:41:35',
                'password' => '$2y$12$uX21Y9BUAVkr1ZCszrvegOeORey2GgVKrplkptTLWaGtpeeSpiYWS',
                'remember_token' => 'ukfmBdU03Q',
                'created_at' => '2025-09-27 00:41:35',
                'updated_at' => '2025-09-27 00:41:35',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 58,
                'name' => 'Kallie Oberbrunner',
                'email' => 'loren.conroy@example.com',
                'email_verified_at' => '2025-09-27 00:48:21',
                'password' => '$2y$12$ZksBv35YLb3ceh4MfEDPLuHgjkaBShkS.hKo15RGw1Cs9GJ04onta',
                'remember_token' => 'wx9pXTCIpp',
                'created_at' => '2025-09-27 00:48:23',
                'updated_at' => '2025-09-27 00:48:23',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 59,
                'name' => 'Colby Torphy',
                'email' => 'theo75@example.org',
                'email_verified_at' => '2025-09-27 00:48:23',
                'password' => '$2y$12$ZksBv35YLb3ceh4MfEDPLuHgjkaBShkS.hKo15RGw1Cs9GJ04onta',
                'remember_token' => '5op93ounCD',
                'created_at' => '2025-09-27 00:48:23',
                'updated_at' => '2025-09-27 00:48:23',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 60,
                'name' => 'Dr. Emmalee Schamberger',
                'email' => 'zshields@example.net',
                'email_verified_at' => '2025-09-27 00:48:23',
                'password' => '$2y$12$ZksBv35YLb3ceh4MfEDPLuHgjkaBShkS.hKo15RGw1Cs9GJ04onta',
                'remember_token' => 'yjVj3f44A4',
                'created_at' => '2025-09-27 00:48:23',
                'updated_at' => '2025-09-27 00:48:23',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 61,
                'name' => 'Marley McGlynn',
                'email' => 'lconnelly@example.org',
                'email_verified_at' => '2025-09-27 00:48:23',
                'password' => '$2y$12$ZksBv35YLb3ceh4MfEDPLuHgjkaBShkS.hKo15RGw1Cs9GJ04onta',
                'remember_token' => 'XffUZgAArw',
                'created_at' => '2025-09-27 00:48:23',
                'updated_at' => '2025-09-27 00:48:23',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 62,
                'name' => 'Fleta Hayes',
                'email' => 'ansley32@example.net',
                'email_verified_at' => '2025-09-27 00:48:23',
                'password' => '$2y$12$ZksBv35YLb3ceh4MfEDPLuHgjkaBShkS.hKo15RGw1Cs9GJ04onta',
                'remember_token' => 'ss8685sbWP',
                'created_at' => '2025-09-27 00:48:23',
                'updated_at' => '2025-09-27 00:48:23',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 63,
                'name' => 'Ms. Melyssa Nolan V',
                'email' => 'wcole@example.com',
                'email_verified_at' => '2025-09-27 00:49:35',
                'password' => '$2y$12$gyvOzjmDfH5w3qQ9dPZJrORhBCjYW0ZHC4EFoPJ/1usGW.ax6eI8C',
                'remember_token' => 'cGQrNMrmFT',
                'created_at' => '2025-09-27 00:49:36',
                'updated_at' => '2025-09-27 00:49:36',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 64,
                'name' => 'Monica Tromp DVM',
                'email' => 'igibson@example.org',
                'email_verified_at' => '2025-09-27 00:49:36',
                'password' => '$2y$12$gyvOzjmDfH5w3qQ9dPZJrORhBCjYW0ZHC4EFoPJ/1usGW.ax6eI8C',
                'remember_token' => '3HEFBuOQUc',
                'created_at' => '2025-09-27 00:49:36',
                'updated_at' => '2025-09-27 00:49:36',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 65,
                'name' => 'Estel Fahey Jr.',
                'email' => 'romaguera.mabel@example.net',
                'email_verified_at' => '2025-09-27 00:49:36',
                'password' => '$2y$12$gyvOzjmDfH5w3qQ9dPZJrORhBCjYW0ZHC4EFoPJ/1usGW.ax6eI8C',
                'remember_token' => '6xZ7NoGMTx',
                'created_at' => '2025-09-27 00:49:36',
                'updated_at' => '2025-09-27 00:49:36',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 66,
                'name' => 'Bud Kuvalis',
                'email' => 'mikayla54@example.net',
                'email_verified_at' => '2025-09-27 00:49:36',
                'password' => '$2y$12$gyvOzjmDfH5w3qQ9dPZJrORhBCjYW0ZHC4EFoPJ/1usGW.ax6eI8C',
                'remember_token' => 'D612oRhbCL',
                'created_at' => '2025-09-27 00:49:36',
                'updated_at' => '2025-09-27 00:49:36',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ],
            [
                'id' => 67,
                'name' => 'Yvonne Flatley DDS',
                'email' => 'block.lennie@example.com',
                'email_verified_at' => '2025-09-27 00:49:36',
                'password' => '$2y$12$gyvOzjmDfH5w3qQ9dPZJrORhBCjYW0ZHC4EFoPJ/1usGW.ax6eI8C',
                'remember_token' => 'beAK7SL7gI',
                'created_at' => '2025-09-27 00:49:36',
                'updated_at' => '2025-09-27 00:49:36',
                'stripe_id' => NULL,
                'pm_type' => NULL,
                'pm_last_four' => NULL,
                'trial_ends_at' => NULL,
            ]
        ];
        
        DB::table("users")->insert($dataTables);
    }
}