<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BuildingTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 13,
                'name' => 'repellat iure',
                'key' => 'rerum-in-molestiae',
                'description' => 'Tenetur sapiente alias similique quaerat quasi.',
                'max_level' => 5,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":274,\\"clay\\":374,\\"iron\\":183,\\"crop\\":405}"',
                'production' => '"[]"',
                'population' => '"[]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:46:17',
                'updated_at' => '2025-09-25 23:46:17',
            ],
            [
                'id' => 14,
                'name' => 'Woodcutter',
                'key' => 'woodcutter',
                'description' => 'Produces wood for your village',
                'max_level' => 20,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":100,\\"clay\\":80,\\"iron\\":50,\\"crop\\":30}"',
                'production' => '"{\\"wood\\":2}"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 15,
                'name' => 'Clay Pit',
                'key' => 'clay_pit',
                'description' => 'Produces clay for your village',
                'max_level' => 20,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":80,\\"clay\\":100,\\"iron\\":50,\\"crop\\":30}"',
                'production' => '"{\\"clay\\":2}"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 16,
                'name' => 'Iron Mine',
                'key' => 'iron_mine',
                'description' => 'Produces iron for your village',
                'max_level' => 20,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":80,\\"clay\\":80,\\"iron\\":100,\\"crop\\":30}"',
                'production' => '"{\\"iron\\":2}"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 17,
                'name' => 'Cropland',
                'key' => 'cropland',
                'description' => 'Produces crop for your village',
                'max_level' => 20,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":80,\\"clay\\":80,\\"iron\\":50,\\"crop\\":100}"',
                'production' => '"{\\"crop\\":2}"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 18,
                'name' => 'Warehouse',
                'key' => 'warehouse',
                'description' => 'Increases storage capacity for resources',
                'max_level' => 20,
                'requirements' => '"{\\"woodcutter\\":1,\\"clay_pit\\":1,\\"iron_mine\\":1}"',
                'costs' => '"{\\"wood\\":130,\\"clay\\":160,\\"iron\\":90,\\"crop\\":40}"',
                'production' => '"[]"',
                'population' => '"[1]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 19,
                'name' => 'Granary',
                'key' => 'granary',
                'description' => 'Increases storage capacity for crop',
                'max_level' => 20,
                'requirements' => '"{\\"cropland\\":1}"',
                'costs' => '"{\\"wood\\":130,\\"clay\\":160,\\"iron\\":90,\\"crop\\":40}"',
                'production' => '"[]"',
                'population' => '"[1]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 20,
                'name' => 'Barracks',
                'key' => 'barracks',
                'description' => 'Trains infantry units',
                'max_level' => 20,
                'requirements' => '"{\\"warehouse\\":1,\\"granary\\":1}"',
                'costs' => '"{\\"wood\\":200,\\"clay\\":200,\\"iron\\":200,\\"crop\\":200}"',
                'production' => '"[]"',
                'population' => '"[4]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 21,
                'name' => 'Academy',
                'key' => 'academy',
                'description' => 'Researches new technologies',
                'max_level' => 20,
                'requirements' => '"{\\"warehouse\\":1,\\"granary\\":1}"',
                'costs' => '"{\\"wood\\":200,\\"clay\\":200,\\"iron\\":200,\\"crop\\":200}"',
                'production' => '"[]"',
                'population' => '"[4]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 22,
                'name' => 'Rally Point',
                'key' => 'rally_point',
                'description' => 'Coordinates troop movements',
                'max_level' => 1,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":110,\\"clay\\":110,\\"iron\\":110,\\"crop\\":110}"',
                'production' => '"[]"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 23,
                'name' => 'Market',
                'key' => 'market',
                'description' => 'Trades resources with other players',
                'max_level' => 20,
                'requirements' => '"{\\"warehouse\\":1,\\"granary\\":1}"',
                'costs' => '"{\\"wood\\":200,\\"clay\\":200,\\"iron\\":200,\\"crop\\":200}"',
                'production' => '"[]"',
                'population' => '"[4]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 24,
                'name' => 'Wall',
                'key' => 'wall',
                'description' => 'Provides defensive bonuses to your village',
                'max_level' => 20,
                'requirements' => '"{\\"main_building\\":1}"',
                'costs' => '"{\\"wood\\":50,\\"clay\\":100,\\"iron\\":20,\\"crop\\":50}"',
                'production' => '"[]"',
                'population' => '"[0]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ],
            [
                'id' => 25,
                'name' => 'Watchtower',
                'key' => 'watchtower',
                'description' => 'Provides early warning and defensive bonuses',
                'max_level' => 20,
                'requirements' => '"{\\"main_building\\":1,\\"wall\\":1}"',
                'costs' => '"{\\"wood\\":100,\\"clay\\":150,\\"iron\\":100,\\"crop\\":80}"',
                'production' => '"[]"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ],
            [
                'id' => 26,
                'name' => 'Trap',
                'key' => 'trap',
                'description' => 'Catches enemy spies and provides defensive bonuses',
                'max_level' => 20,
                'requirements' => '"{\\"main_building\\":1,\\"wall\\":1}"',
                'costs' => '"{\\"wood\\":80,\\"clay\\":120,\\"iron\\":80,\\"crop\\":60}"',
                'production' => '"[]"',
                'population' => '"[1]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ],
            [
                'id' => 27,
                'name' => 'Stable',
                'key' => 'stable',
                'description' => 'Trains cavalry units',
                'max_level' => 20,
                'requirements' => '"{\\"main_building\\":3,\\"barracks\\":5}"',
                'costs' => '"{\\"wood\\":200,\\"clay\\":150,\\"iron\\":100,\\"crop\\":80}"',
                'production' => '"[]"',
                'population' => '"[3]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ],
            [
                'id' => 28,
                'name' => 'Workshop',
                'key' => 'workshop',
                'description' => 'Builds siege weapons',
                'max_level' => 20,
                'requirements' => '"{\\"main_building\\":5,\\"barracks\\":10}"',
                'costs' => '"{\\"wood\\":300,\\"clay\\":200,\\"iron\\":250,\\"crop\\":100}"',
                'production' => '"[]"',
                'population' => '"[4]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ],
            [
                'id' => 29,
                'name' => 'Smithy',
                'key' => 'smithy',
                'description' => 'Researches military technologies',
                'max_level' => 20,
                'requirements' => '"{\\"main_building\\":3,\\"barracks\\":1}"',
                'costs' => '"{\\"wood\\":200,\\"clay\\":150,\\"iron\\":100,\\"crop\\":50}"',
                'production' => '"[]"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ],
            [
                'id' => 30,
                'name' => 'Main Building',
                'key' => 'main_building',
                'description' => 'The heart of your village',
                'max_level' => 20,
                'requirements' => '"[]"',
                'costs' => '"{\\"wood\\":100,\\"clay\\":80,\\"iron\\":60,\\"crop\\":40}"',
                'production' => '"[]"',
                'population' => '"[2]"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:46:56',
                'updated_at' => '2025-09-27 00:46:56',
            ]
        ];
        
        foreach ($dataTables as $data) {
            DB::table("building_types")->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}