<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BuildingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1435,
                'village_id' => 143,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:42:29',
                'updated_at' => '2025-09-27 00:42:29',
            ],
            [
                'id' => 1436,
                'village_id' => 144,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:05',
                'updated_at' => '2025-09-27 00:43:05',
            ],
            [
                'id' => 1437,
                'village_id' => 144,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:05',
                'updated_at' => '2025-09-27 00:43:05',
            ],
            [
                'id' => 1438,
                'village_id' => 144,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:05',
                'updated_at' => '2025-09-27 00:43:05',
            ],
            [
                'id' => 1439,
                'village_id' => 144,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:05',
                'updated_at' => '2025-09-27 00:43:05',
            ],
            [
                'id' => 1444,
                'village_id' => 146,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:32',
                'updated_at' => '2025-09-27 00:43:32',
            ],
            [
                'id' => 1445,
                'village_id' => 146,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:32',
                'updated_at' => '2025-09-27 00:43:32',
            ],
            [
                'id' => 1446,
                'village_id' => 146,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:32',
                'updated_at' => '2025-09-27 00:43:32',
            ],
            [
                'id' => 1447,
                'village_id' => 146,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:43:32',
                'updated_at' => '2025-09-27 00:43:32',
            ],
            [
                'id' => 1448,
                'village_id' => 147,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 1449,
                'village_id' => 147,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 1450,
                'village_id' => 147,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 1451,
                'village_id' => 147,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 1456,
                'village_id' => 149,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:45:03',
                'updated_at' => '2025-09-27 00:45:03',
            ],
            [
                'id' => 1457,
                'village_id' => 149,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:45:03',
                'updated_at' => '2025-09-27 00:45:03',
            ],
            [
                'id' => 1458,
                'village_id' => 149,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:45:03',
                'updated_at' => '2025-09-27 00:45:03',
            ],
            [
                'id' => 1459,
                'village_id' => 149,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:45:03',
                'updated_at' => '2025-09-27 00:45:03',
            ],
            [
                'id' => 1468,
                'village_id' => 152,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:47:24',
                'updated_at' => '2025-09-27 00:47:24',
            ],
            [
                'id' => 1469,
                'village_id' => 152,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:47:24',
                'updated_at' => '2025-09-27 00:47:24',
            ],
            [
                'id' => 1470,
                'village_id' => 152,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:47:24',
                'updated_at' => '2025-09-27 00:47:24',
            ],
            [
                'id' => 1471,
                'village_id' => 152,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:47:24',
                'updated_at' => '2025-09-27 00:47:24',
            ],
            [
                'id' => 1472,
                'village_id' => 153,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:21',
                'updated_at' => '2025-09-27 00:48:21',
            ],
            [
                'id' => 1473,
                'village_id' => 153,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:21',
                'updated_at' => '2025-09-27 00:48:21',
            ],
            [
                'id' => 1474,
                'village_id' => 153,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:21',
                'updated_at' => '2025-09-27 00:48:21',
            ],
            [
                'id' => 1475,
                'village_id' => 153,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:21',
                'updated_at' => '2025-09-27 00:48:21',
            ],
            [
                'id' => 1476,
                'village_id' => 154,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:34',
                'updated_at' => '2025-09-27 00:48:34',
            ],
            [
                'id' => 1477,
                'village_id' => 154,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:34',
                'updated_at' => '2025-09-27 00:48:34',
            ],
            [
                'id' => 1478,
                'village_id' => 154,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:34',
                'updated_at' => '2025-09-27 00:48:34',
            ],
            [
                'id' => 1479,
                'village_id' => 154,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:48:34',
                'updated_at' => '2025-09-27 00:48:34',
            ],
            [
                'id' => 1480,
                'village_id' => 155,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:12',
                'updated_at' => '2025-09-27 00:49:12',
            ],
            [
                'id' => 1481,
                'village_id' => 155,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:12',
                'updated_at' => '2025-09-27 00:49:12',
            ],
            [
                'id' => 1482,
                'village_id' => 155,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:12',
                'updated_at' => '2025-09-27 00:49:12',
            ],
            [
                'id' => 1483,
                'village_id' => 155,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:12',
                'updated_at' => '2025-09-27 00:49:12',
            ],
            [
                'id' => 1484,
                'village_id' => 156,
                'building_type_id' => 13,
                'name' => NULL,
                'level' => 1,
                'x' => 0,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 1485,
                'village_id' => 156,
                'building_type_id' => 14,
                'name' => NULL,
                'level' => 1,
                'x' => 1,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 1486,
                'village_id' => 156,
                'building_type_id' => 15,
                'name' => NULL,
                'level' => 1,
                'x' => 2,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 1487,
                'village_id' => 156,
                'building_type_id' => 16,
                'name' => NULL,
                'level' => 1,
                'x' => 3,
                'y' => 0,
                'is_active' => 1,
                'upgrade_started_at' => NULL,
                'upgrade_completed_at' => NULL,
                'metadata' => NULL,
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ]
        ];
        
        foreach ($dataTables as $data) {
            DB::table("buildings")->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}