<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GameConfigsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'key' => 'game_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Game speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 2,
                'key' => 'unit_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Unit movement speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 3,
                'key' => 'trade_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Trade speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 4,
                'key' => 'world_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'World speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 5,
                'key' => 'resource_multiplier',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Resource production multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 6,
                'key' => 'storage_multiplier',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Storage capacity multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 7,
                'key' => 'crop_consumption',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Crop consumption multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 8,
                'key' => 'building_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Building construction speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 9,
                'key' => 'research_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Research speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 10,
                'key' => 'training_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Unit training speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 11,
                'key' => 'combat_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Combat speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 12,
                'key' => 'morale_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Morale speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 13,
                'key' => 'artefact_speed',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Artifact speed multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 14,
                'key' => 'world_size',
                'value' => 401,
                'type' => 'integer',
                'description' => 'World size (401x401]',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 15,
                'key' => 'village_distance',
                'value' => 7,
                'type' => 'integer',
                'description' => 'Minimum distance between villages',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 16,
                'key' => 'oasis_distance',
                'value' => 5,
                'type' => 'integer',
                'description' => 'Minimum distance between oases',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 17,
                'key' => 'plus_features',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable Plus features',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 18,
                'key' => 'alliance_features',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable Alliance features',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 19,
                'key' => 'hero_features',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable Hero features',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 20,
                'key' => 'artefact_features',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable Artifact features',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 21,
                'key' => 'tick_time',
                'value' => 60,
                'type' => 'integer',
                'description' => 'Game tick time in seconds',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 22,
                'key' => 'resource_update_interval',
                'value' => 60,
                'type' => 'integer',
                'description' => 'Resource update interval in seconds',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 23,
                'key' => 'building_update_interval',
                'value' => 60,
                'type' => 'integer',
                'description' => 'Building update interval in seconds',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 24,
                'key' => 'market_tax',
                'value' => '0.05',
                'type' => 'decimal',
                'description' => 'Market trade tax (5%]',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 25,
                'key' => 'alliance_tax',
                'value' => '0.01',
                'type' => 'decimal',
                'description' => 'Alliance tax (1%]',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 26,
                'key' => 'gold_multiplier',
                'value' => 1,
                'type' => 'integer',
                'description' => 'Gold production multiplier',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 27,
                'key' => 'max_login_attempts',
                'value' => 5,
                'type' => 'integer',
                'description' => 'Maximum login attempts',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 28,
                'key' => 'session_timeout',
                'value' => 3600,
                'type' => 'integer',
                'description' => 'Session timeout in seconds',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 29,
                'key' => 'password_min_length',
                'value' => 6,
                'type' => 'integer',
                'description' => 'Minimum password length',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 30,
                'key' => 'email_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable email notifications',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 31,
                'key' => 'push_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable push notifications',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 32,
                'key' => 'battle_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'description' => 'Enable battle notifications',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 33,
                'key' => 'maintenance_mode',
                'value' => 'false',
                'type' => 'boolean',
                'description' => 'Maintenance mode',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 34,
                'key' => 'maintenance_message',
                'value' => 'Server is under maintenance',
                'type' => 'string',
                'description' => 'Maintenance message',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ],
            [
                'id' => 35,
                'key' => 'backup_interval',
                'value' => 3600,
                'type' => 'integer',
                'description' => 'Backup interval in seconds',
                'created_at' => '2025-09-27 00:49:35',
                'updated_at' => '2025-09-27 00:49:35',
            ]
        ];
        
        foreach ($dataTables as $data) {
            DB::table("game_configs")->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}