<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeroesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         */
        $dataTables = [
            [
                'id' => 1,

                'player_id' => 7,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 2,

                'player_id' => 7,
                'name' => 'Bard',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 3,

                'player_id' => 7,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 4,

                'player_id' => 7,
                'name' => 'Odin',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 5,

                'player_id' => 7,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 6,

                'player_id' => 7,
                'name' => 'Hadrian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 7,

                'player_id' => 7,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 8,

                'player_id' => 7,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 9,

                'player_id' => 7,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 10,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 11,

                'player_id' => 7,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 12,

                'player_id' => 7,
                'name' => 'Ragnar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 13,

                'player_id' => 7,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 14,

                'player_id' => 7,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 15,

                'player_id' => 7,
                'name' => 'Bard',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 16,

                'player_id' => 7,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 17,

                'player_id' => 7,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 18,

                'player_id' => 7,
                'name' => 'Crystal Sage',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 19,

                'player_id' => 7,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 20,

                'player_id' => 7,
                'name' => 'Mystic Defender',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 21,

                'player_id' => 7,
                'name' => 'Asterix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 22,

                'player_id' => 7,
                'name' => 'Asterix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 23,

                'player_id' => 7,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 24,

                'player_id' => 7,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 25,

                'player_id' => 7,
                'name' => 'Julius Caesar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 26,

                'player_id' => 7,
                'name' => 'Beowulf',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 27,

                'player_id' => 7,
                'name' => 'Shadow Knight',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 28,

                'player_id' => 7,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 29,

                'player_id' => 7,
                'name' => 'Ancient Warrior',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 30,

                'player_id' => 7,
                'name' => 'Bard',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 31,

                'player_id' => 7,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 32,

                'player_id' => 7,
                'name' => 'Beowulf',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 33,

                'player_id' => 7,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 34,

                'player_id' => 7,
                'name' => 'Siegfried',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 35,

                'player_id' => 7,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 36,

                'player_id' => 7,
                'name' => 'Ancient Warrior',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 37,

                'player_id' => 7,
                'name' => 'Vercingetorix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 38,

                'player_id' => 7,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 39,

                'player_id' => 7,
                'name' => 'Hadrian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 40,

                'player_id' => 7,
                'name' => 'Shadow Knight',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 41,

                'player_id' => 7,
                'name' => 'Vercingetorix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 42,

                'player_id' => 7,
                'name' => 'Vercingetorix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 43,

                'player_id' => 7,
                'name' => 'Siegfried',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 44,

                'player_id' => 7,
                'name' => 'Mystic Defender',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 45,

                'player_id' => 7,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 46,

                'player_id' => 7,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 47,

                'player_id' => 7,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 48,

                'player_id' => 7,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 49,

                'player_id' => 7,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 50,

                'player_id' => 7,
                'name' => 'Crystal Sage',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 51,

                'player_id' => 7,
                'name' => 'Julius Caesar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 52,

                'player_id' => 7,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 53,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 54,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 55,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 56,

                'player_id' => 7,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 57,

                'player_id' => 7,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 58,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 59,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 60,

                'player_id' => 7,
                'name' => 'Julius Caesar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 61,

                'player_id' => 7,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
        ];

        foreach ($dataTables as $data) {
            DB::table('heroes')->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}
