<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeroesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'reference_number' => NULL,
                'player_id' => 1,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 2,
                'reference_number' => NULL,
                'player_id' => 2,
                'name' => 'Bard',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 3,
                'reference_number' => NULL,
                'player_id' => 3,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 4,
                'reference_number' => NULL,
                'player_id' => 4,
                'name' => 'Odin',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 5,
                'reference_number' => NULL,
                'player_id' => 5,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 6,
                'reference_number' => NULL,
                'player_id' => 6,
                'name' => 'Hadrian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 7,
                'reference_number' => NULL,
                'player_id' => 7,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 8,
                'reference_number' => NULL,
                'player_id' => 8,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 9,
                'reference_number' => NULL,
                'player_id' => 9,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 10,
                'reference_number' => NULL,
                'player_id' => 10,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 11,
                'reference_number' => NULL,
                'player_id' => 11,
                'name' => 'Druid',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 12,
                'reference_number' => NULL,
                'player_id' => 12,
                'name' => 'Ragnar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 13,
                'reference_number' => NULL,
                'player_id' => 13,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 14,
                'reference_number' => NULL,
                'player_id' => 14,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 15,
                'reference_number' => NULL,
                'player_id' => 15,
                'name' => 'Bard',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 16,
                'reference_number' => NULL,
                'player_id' => 16,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 17,
                'reference_number' => NULL,
                'player_id' => 17,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 18,
                'reference_number' => NULL,
                'player_id' => 18,
                'name' => 'Crystal Sage',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 19,
                'reference_number' => NULL,
                'player_id' => 19,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 20,
                'reference_number' => NULL,
                'player_id' => 20,
                'name' => 'Mystic Defender',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 21,
                'reference_number' => NULL,
                'player_id' => 21,
                'name' => 'Asterix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 22,
                'reference_number' => NULL,
                'player_id' => 22,
                'name' => 'Asterix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 23,
                'reference_number' => NULL,
                'player_id' => 23,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 24,
                'reference_number' => NULL,
                'player_id' => 24,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 25,
                'reference_number' => NULL,
                'player_id' => 25,
                'name' => 'Julius Caesar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 26,
                'reference_number' => NULL,
                'player_id' => 26,
                'name' => 'Beowulf',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 27,
                'reference_number' => NULL,
                'player_id' => 27,
                'name' => 'Shadow Knight',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 28,
                'reference_number' => NULL,
                'player_id' => 28,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 29,
                'reference_number' => NULL,
                'player_id' => 29,
                'name' => 'Ancient Warrior',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 30,
                'reference_number' => NULL,
                'player_id' => 30,
                'name' => 'Bard',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 31,
                'reference_number' => NULL,
                'player_id' => 31,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 32,
                'reference_number' => NULL,
                'player_id' => 32,
                'name' => 'Beowulf',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 33,
                'reference_number' => NULL,
                'player_id' => 33,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 34,
                'reference_number' => NULL,
                'player_id' => 34,
                'name' => 'Siegfried',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 35,
                'reference_number' => NULL,
                'player_id' => 35,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 36,
                'reference_number' => NULL,
                'player_id' => 36,
                'name' => 'Ancient Warrior',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 37,
                'reference_number' => NULL,
                'player_id' => 37,
                'name' => 'Vercingetorix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 38,
                'reference_number' => NULL,
                'player_id' => 38,
                'name' => 'Thor',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 39,
                'reference_number' => NULL,
                'player_id' => 39,
                'name' => 'Hadrian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 40,
                'reference_number' => NULL,
                'player_id' => 40,
                'name' => 'Shadow Knight',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 41,
                'reference_number' => NULL,
                'player_id' => 41,
                'name' => 'Vercingetorix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 42,
                'reference_number' => NULL,
                'player_id' => 42,
                'name' => 'Vercingetorix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 43,
                'reference_number' => NULL,
                'player_id' => 43,
                'name' => 'Siegfried',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"berserker_rage\\":{\\"name\\":\\"Berserker Rage\\",\\"description\\":\\"Increases attack power by 30% when health is low\\"},\\"fearless_charge\\":{\\"name\\":\\"Fearless Charge\\",\\"description\\":\\"Cavalry units move 25% faster\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 44,
                'reference_number' => NULL,
                'player_id' => 44,
                'name' => 'Mystic Defender',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 45,
                'reference_number' => NULL,
                'player_id' => 45,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 46,
                'reference_number' => NULL,
                'player_id' => 46,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 47,
                'reference_number' => NULL,
                'player_id' => 47,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 48,
                'reference_number' => NULL,
                'player_id' => 48,
                'name' => 'Natarian Guardian',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 49,
                'reference_number' => NULL,
                'player_id' => 49,
                'name' => 'Obelix',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"nature_blessing\\":{\\"name\\":\\"Nature Blessing\\",\\"description\\":\\"Increases resource production by 15%\\"},\\"druidic_wisdom\\":{\\"name\\":\\"Druidic Wisdom\\",\\"description\\":\\"Reduces building construction time by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 50,
                'reference_number' => NULL,
                'player_id' => 50,
                'name' => 'Crystal Sage',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"ancient_power\\":{\\"name\\":\\"Ancient Power\\",\\"description\\":\\"All units gain 25% bonus to all stats\\"},\\"mystic_shield\\":{\\"name\\":\\"Mystic Shield\\",\\"description\\":\\"Reduces incoming damage by 20%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 51,
                'reference_number' => NULL,
                'player_id' => 51,
                'name' => 'Julius Caesar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 52,
                'reference_number' => NULL,
                'player_id' => 52,
                'name' => 'Augustus',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 53,
                'reference_number' => NULL,
                'player_id' => 53,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 54,
                'reference_number' => NULL,
                'player_id' => 55,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 55,
                'reference_number' => NULL,
                'player_id' => 56,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 56,
                'reference_number' => NULL,
                'player_id' => 58,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 57,
                'reference_number' => NULL,
                'player_id' => 61,
                'name' => 'Trajan',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 58,
                'reference_number' => NULL,
                'player_id' => 62,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 59,
                'reference_number' => NULL,
                'player_id' => 63,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 60,
                'reference_number' => NULL,
                'player_id' => 64,
                'name' => 'Julius Caesar',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ],
            [
                'id' => 61,
                'reference_number' => NULL,
                'player_id' => 65,
                'name' => 'Marcus Aurelius',
                'level' => 1,
                'experience' => 0,
                'attack_power' => 100,
                'defense_power' => 100,
                'health' => 1000,
                'max_health' => 1000,
                'special_abilities' => '"{\\"legion_leadership\\":{\\"name\\":\\"Legion Leadership\\",\\"description\\":\\"Increases infantry attack by 20%\\"},\\"tactical_brilliance\\":{\\"name\\":\\"Tactical Brilliance\\",\\"description\\":\\"Reduces enemy defense by 15%\\"}}"',
                'equipment' => '"[]"',
                'is_active' => 1,
                'created_at' => '2025-09-27 01:21:15',
                'updated_at' => '2025-09-27 01:21:15',
            ]
        ];
        
        foreach ($dataTables as $data) {
            DB::table("heroes")->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}