<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlayerQuestsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'reference_number' => NULL,
                'player_id' => 1,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 2,
                'reference_number' => NULL,
                'player_id' => 2,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 3,
                'reference_number' => NULL,
                'player_id' => 3,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 4,
                'reference_number' => NULL,
                'player_id' => 4,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 5,
                'reference_number' => NULL,
                'player_id' => 5,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 6,
                'reference_number' => NULL,
                'player_id' => 6,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 7,
                'reference_number' => NULL,
                'player_id' => 7,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 8,
                'reference_number' => NULL,
                'player_id' => 8,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 9,
                'reference_number' => NULL,
                'player_id' => 9,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 10,
                'reference_number' => NULL,
                'player_id' => 10,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 11,
                'reference_number' => NULL,
                'player_id' => 11,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 12,
                'reference_number' => NULL,
                'player_id' => 12,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 13,
                'reference_number' => NULL,
                'player_id' => 13,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 14,
                'reference_number' => NULL,
                'player_id' => 14,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 15,
                'reference_number' => NULL,
                'player_id' => 15,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 16,
                'reference_number' => NULL,
                'player_id' => 16,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 17,
                'reference_number' => NULL,
                'player_id' => 17,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 18,
                'reference_number' => NULL,
                'player_id' => 18,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 19,
                'reference_number' => NULL,
                'player_id' => 19,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 20,
                'reference_number' => NULL,
                'player_id' => 20,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 21,
                'reference_number' => NULL,
                'player_id' => 21,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 22,
                'reference_number' => NULL,
                'player_id' => 22,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 23,
                'reference_number' => NULL,
                'player_id' => 23,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 24,
                'reference_number' => NULL,
                'player_id' => 24,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 25,
                'reference_number' => NULL,
                'player_id' => 25,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 26,
                'reference_number' => NULL,
                'player_id' => 26,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 27,
                'reference_number' => NULL,
                'player_id' => 27,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 28,
                'reference_number' => NULL,
                'player_id' => 28,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 29,
                'reference_number' => NULL,
                'player_id' => 29,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 30,
                'reference_number' => NULL,
                'player_id' => 30,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 31,
                'reference_number' => NULL,
                'player_id' => 31,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 32,
                'reference_number' => NULL,
                'player_id' => 32,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 33,
                'reference_number' => NULL,
                'player_id' => 33,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 34,
                'reference_number' => NULL,
                'player_id' => 34,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 35,
                'reference_number' => NULL,
                'player_id' => 35,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 36,
                'reference_number' => NULL,
                'player_id' => 36,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 37,
                'reference_number' => NULL,
                'player_id' => 37,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 38,
                'reference_number' => NULL,
                'player_id' => 38,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 39,
                'reference_number' => NULL,
                'player_id' => 39,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 40,
                'reference_number' => NULL,
                'player_id' => 40,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 41,
                'reference_number' => NULL,
                'player_id' => 41,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 42,
                'reference_number' => NULL,
                'player_id' => 42,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 43,
                'reference_number' => NULL,
                'player_id' => 43,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 44,
                'reference_number' => NULL,
                'player_id' => 44,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 45,
                'reference_number' => NULL,
                'player_id' => 45,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 46,
                'reference_number' => NULL,
                'player_id' => 46,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 47,
                'reference_number' => NULL,
                'player_id' => 47,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 48,
                'reference_number' => NULL,
                'player_id' => 48,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 49,
                'reference_number' => NULL,
                'player_id' => 49,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 50,
                'reference_number' => NULL,
                'player_id' => 50,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 51,
                'reference_number' => NULL,
                'player_id' => 51,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 52,
                'reference_number' => NULL,
                'player_id' => 52,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 53,
                'reference_number' => NULL,
                'player_id' => 53,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 54,
                'reference_number' => NULL,
                'player_id' => 55,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 55,
                'reference_number' => NULL,
                'player_id' => 56,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 56,
                'reference_number' => NULL,
                'player_id' => 58,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 57,
                'reference_number' => NULL,
                'player_id' => 61,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 58,
                'reference_number' => NULL,
                'player_id' => 62,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 59,
                'reference_number' => NULL,
                'player_id' => 63,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 60,
                'reference_number' => NULL,
                'player_id' => 64,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 61,
                'reference_number' => NULL,
                'player_id' => 65,
                'quest_id' => 1,
                'status' => 'available',
                'progress' => 0,
                'progress_data' => '[]',
                'started_at' => NULL,
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 00:57:49',
                'updated_at' => '2025-09-27 00:57:49',
            ],
            [
                'id' => 63,
                'reference_number' => 'PQ-2025090003',
                'player_id' => 1,
                'quest_id' => 2,
                'status' => 'in_progress',
                'progress' => 0,
                'progress_data' => NULL,
                'started_at' => '2025-09-27 01:05:27',
                'completed_at' => NULL,
                'expires_at' => NULL,
                'created_at' => '2025-09-27 01:05:27',
                'updated_at' => '2025-09-27 01:05:27',
            ]
        ];
        
        DB::table("player_quests")->insert($dataTables);
    }
}