<?php

namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         */
        $dataTables = [
            [
                'id' => 1,
                'reference_number' => null,
                'name' => 'Welcome to Travian',
                'key' => 'welcome',
                'description' => 'Welcome to the world of Travian! Complete this quest to get started.',
                'instructions' => null,
                'category' => 'tutorial',
                'difficulty' => 1,
                'requirements' => '"[]"',
                'rewards' => '"{\"resources\":{\"wood\":1000,\"clay\":1000,\"iron\":1000,\"crop\":1000}}"',
                'experience_reward' => 0,
                'gold_reward' => 0,
                'resource_rewards' => null,
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 2,
                'reference_number' => null,
                'name' => 'First Building',
                'key' => 'first_building',
                'description' => 'Build your first building to expand your village.',
                'instructions' => null,
                'category' => 'building',
                'difficulty' => 1,
                'requirements' => '"{\"buildings\":{\"main_building\":1}}"',
                'rewards' => '"{\"resources\":{\"wood\":500,\"clay\":500,\"iron\":500,\"crop\":500}}"',
                'experience_reward' => 0,
                'gold_reward' => 0,
                'resource_rewards' => null,
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 3,
                'reference_number' => null,
                'name' => 'Resource Production',
                'key' => 'resource_production',
                'description' => 'Upgrade your resource buildings to increase production.',
                'instructions' => null,
                'category' => 'building',
                'difficulty' => 2,
                'requirements' => '"{\"buildings\":{\"woodcutter\":5,\"clay_pit\":5,\"iron_mine\":5,\"crop_field\":5}}"',
                'rewards' => '"{\"resources\":{\"wood\":2000,\"clay\":2000,\"iron\":2000,\"crop\":2000}}"',
                'experience_reward' => 0,
                'gold_reward' => 0,
                'resource_rewards' => null,
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 4,
                'reference_number' => null,
                'name' => 'Military Training',
                'key' => 'military_training',
                'description' => 'Train your first military units.',
                'instructions' => null,
                'category' => 'combat',
                'difficulty' => 2,
                'requirements' => '"{\"buildings\":{\"barracks\":3},\"units\":{\"legionnaire\":10}}"',
                'rewards' => '"{\"resources\":{\"wood\":1000,\"clay\":1000,\"iron\":1000,\"crop\":1000}}"',
                'experience_reward' => 0,
                'gold_reward' => 0,
                'resource_rewards' => null,
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 5,
                'reference_number' => null,
                'name' => 'Village Expansion',
                'key' => 'village_expansion',
                'description' => 'Expand your village by building more structures.',
                'instructions' => null,
                'category' => 'building',
                'difficulty' => 3,
                'requirements' => '"{\"buildings\":{\"main_building\":10,\"warehouse\":5,\"granary\":5}}"',
                'rewards' => '"{\"resources\":{\"wood\":5000,\"clay\":5000,\"iron\":5000,\"crop\":5000}}"',
                'experience_reward' => 0,
                'gold_reward' => 0,
                'resource_rewards' => null,
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 6,

                'name' => 'Resource Storage',
                'key' => 'resource_storage',
                'description' => 'Build storage buildings to increase your resource capacity.',
                'instructions' => null,
                'category' => 'building',
                'difficulty' => 1,
                'requirements' => '"{\"build_warehouse\":1,\"build_granary\":1}"',
                'rewards' => '"{\"wood\":1000,\"clay\":1000,\"iron\":1000,\"crop\":1000}"',
                'experience_reward' => 75,
                'gold_reward' => 0,
                'resource_rewards' => '"{\"wood\":1000,\"clay\":1000,\"iron\":1000,\"crop\":1000}"',
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 7,

                'name' => 'Research and Development',
                'key' => 'research_development',
                'description' => 'Learn about research and technology.',
                'instructions' => null,
                'category' => 'building',
                'difficulty' => 2,
                'requirements' => '"{\"build_academy\":1,\"research_first_tech\":true}"',
                'rewards' => '"{\"wood\":3000,\"clay\":3000,\"iron\":3000,\"crop\":3000}"',
                'experience_reward' => 200,
                'gold_reward' => 0,
                'resource_rewards' => '"{\"wood\":3000,\"clay\":3000,\"iron\":3000,\"crop\":3000}"',
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 8,

                'name' => 'First Battle',
                'key' => 'first_battle',
                'description' => 'Launch your first attack on another village.',
                'instructions' => null,
                'category' => 'combat',
                'difficulty' => 3,
                'requirements' => '"{\"launch_attack\":1}"',
                'rewards' => '"{\"wood\":5000,\"clay\":5000,\"iron\":5000,\"crop\":5000}"',
                'experience_reward' => 300,
                'gold_reward' => 0,
                'resource_rewards' => '"{\"wood\":5000,\"clay\":5000,\"iron\":5000,\"crop\":5000}"',
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 9,

                'name' => 'Exploration',
                'key' => 'exploration',
                'description' => 'Explore the world map and discover new villages.',
                'instructions' => null,
                'category' => 'exploration',
                'difficulty' => 2,
                'requirements' => '"{\"explore_villages\":5}"',
                'rewards' => '"{\"wood\":1000,\"clay\":1000,\"iron\":1000,\"crop\":1000}"',
                'experience_reward' => 100,
                'gold_reward' => 0,
                'resource_rewards' => '"{\"wood\":1000,\"clay\":1000,\"iron\":1000,\"crop\":1000}"',
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 10,

                'name' => 'Trade Master',
                'key' => 'trade_master',
                'description' => 'Complete your first trade on the market.',
                'instructions' => null,
                'category' => 'trade',
                'difficulty' => 2,
                'requirements' => '"{\"complete_trade\":1}"',
                'rewards' => '"{\"wood\":2000,\"clay\":2000,\"iron\":2000,\"crop\":2000}"',
                'experience_reward' => 150,
                'gold_reward' => 0,
                'resource_rewards' => '"{\"wood\":2000,\"clay\":2000,\"iron\":2000,\"crop\":2000}"',
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 11,

                'name' => 'Alliance Builder',
                'key' => 'alliance_builder',
                'description' => 'Join or create an alliance.',
                'instructions' => null,
                'category' => 'alliance',
                'difficulty' => 3,
                'requirements' => '"{\"join_alliance\":1}"',
                'rewards' => '"{\"wood\":3000,\"clay\":3000,\"iron\":3000,\"crop\":3000}"',
                'experience_reward' => 250,
                'gold_reward' => 0,
                'resource_rewards' => '"{\"wood\":3000,\"clay\":3000,\"iron\":3000,\"crop\":3000}"',
                'is_repeatable' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
            [
                'id' => 12,

                'name' => 'Special Mission',
                'key' => 'special_mission',
                'description' => 'Complete a special mission for extra rewards.',
                'instructions' => null,
                'category' => 'special',
                'difficulty' => 4,
                'requirements' => '"{\"complete_special_task\":1}"',
                'rewards' => '"{\"wood\":10000,\"clay\":10000,\"iron\":10000,\"crop\":10000}"',
                'experience_reward' => 500,
                'gold_reward' => 100,
                'resource_rewards' => '"{\"wood\":10000,\"clay\":10000,\"iron\":10000,\"crop\":10000}"',
                'is_repeatable' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:44:30',
                'updated_at' => '2025-09-27 00:44:30',
            ],
        ];

        foreach ($dataTables as $data) {
            DB::table('quests')->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}
