<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaxonomiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'name' => 'Tutorial',
                'slug' => 'tutorial',
                'type' => 'quest_category',
                'description' => 'Tutorial and learning quests for new players',
                'parent_id' => NULL,
                'sort_order' => 1,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'meta' => '{"icon":"book-open","color":"#3b82f6","order":1}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'name' => 'Building',
                'slug' => 'building',
                'type' => 'quest_category',
                'description' => 'Quests related to building construction and upgrades',
                'parent_id' => NULL,
                'sort_order' => 2,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'meta' => '{"icon":"building","color":"#10b981","order":2}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'name' => 'Combat',
                'slug' => 'combat',
                'type' => 'quest_category',
                'description' => 'Military and combat-related quests',
                'parent_id' => NULL,
                'sort_order' => 3,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'meta' => '{"icon":"sword","color":"#ef4444","order":3}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'name' => 'Resource Management',
                'slug' => 'resource',
                'type' => 'quest_category',
                'description' => 'Quests about resource gathering and management',
                'parent_id' => NULL,
                'sort_order' => 4,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'meta' => '{"icon":"coins","color":"#f59e0b","order":4}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 5,
                'name' => 'Exploration',
                'slug' => 'exploration',
                'type' => 'quest_category',
                'description' => 'Quests involving world exploration and discovery',
                'parent_id' => NULL,
                'sort_order' => 5,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'meta' => '{"icon":"map","color":"#8b5cf6","order":5}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'name' => 'Diplomacy',
                'slug' => 'diplomacy',
                'type' => 'quest_category',
                'description' => 'Alliance and diplomatic quests',
                'parent_id' => NULL,
                'sort_order' => 6,
                'lft' => 11,
                'rgt' => 12,
                'depth' => 0,
                'meta' => '{"icon":"handshake","color":"#06b6d4","order":6}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'name' => 'Beginner',
                'slug' => 'beginner',
                'type' => 'quest_difficulty',
                'description' => 'Easy quests for new players',
                'parent_id' => NULL,
                'sort_order' => 1,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'meta' => '{"icon":"star","color":"#22c55e","order":1,"experience_multiplier":1}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'name' => 'Intermediate',
                'slug' => 'intermediate',
                'type' => 'quest_difficulty',
                'description' => 'Moderate difficulty quests',
                'parent_id' => NULL,
                'sort_order' => 2,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'meta' => '{"icon":"star","color":"#f59e0b","order":2,"experience_multiplier":1.5}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 9,
                'name' => 'Advanced',
                'slug' => 'advanced',
                'type' => 'quest_difficulty',
                'description' => 'Challenging quests for experienced players',
                'parent_id' => NULL,
                'sort_order' => 3,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'meta' => '{"icon":"star","color":"#ef4444","order":3,"experience_multiplier":2}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 10,
                'name' => 'Expert',
                'slug' => 'expert',
                'type' => 'quest_difficulty',
                'description' => 'Very difficult quests for expert players',
                'parent_id' => NULL,
                'sort_order' => 4,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'meta' => '{"icon":"star","color":"#8b5cf6","order":4,"experience_multiplier":3}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 11,
                'name' => 'Legendary',
                'slug' => 'legendary',
                'type' => 'quest_difficulty',
                'description' => 'Extremely challenging legendary quests',
                'parent_id' => NULL,
                'sort_order' => 5,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'meta' => '{"icon":"star","color":"#f97316","order":5,"experience_multiplier":5}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 12,
                'name' => 'Resource Buildings',
                'slug' => 'resource',
                'type' => 'building_category',
                'description' => 'Buildings that produce resources',
                'parent_id' => NULL,
                'sort_order' => 1,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'meta' => '{"icon":"factory","color":"#f59e0b","order":1}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 13,
                'name' => 'Military Buildings',
                'slug' => 'military',
                'type' => 'building_category',
                'description' => 'Buildings for military purposes',
                'parent_id' => NULL,
                'sort_order' => 2,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'meta' => '{"icon":"shield","color":"#ef4444","order":2}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 14,
                'name' => 'Infrastructure',
                'slug' => 'infrastructure',
                'type' => 'building_category',
                'description' => 'Basic infrastructure buildings',
                'parent_id' => NULL,
                'sort_order' => 3,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'meta' => '{"icon":"home","color":"#6b7280","order":3}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 15,
                'name' => 'Special Buildings',
                'slug' => 'special',
                'type' => 'building_category',
                'description' => 'Unique and special purpose buildings',
                'parent_id' => NULL,
                'sort_order' => 4,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'meta' => '{"icon":"sparkles","color":"#8b5cf6","order":4}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 16,
                'name' => 'Defense',
                'slug' => 'defense',
                'type' => 'building_category',
                'description' => 'Defensive structures and fortifications',
                'parent_id' => NULL,
                'sort_order' => 5,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'meta' => '{"icon":"wall","color":"#374151","order":5}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 17,
                'name' => 'Romans',
                'slug' => 'romans',
                'type' => 'unit_tribe',
                'description' => 'Roman civilization units',
                'parent_id' => NULL,
                'sort_order' => 1,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'meta' => '{"icon":"shield","color":"#dc2626","order":1,"specialty":"infantry"}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 18,
                'name' => 'Teutons',
                'slug' => 'teutons',
                'type' => 'unit_tribe',
                'description' => 'Teutonic civilization units',
                'parent_id' => NULL,
                'sort_order' => 2,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'meta' => '{"icon":"sword","color":"#059669","order":2,"specialty":"cavalry"}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 19,
                'name' => 'Gauls',
                'slug' => 'gauls',
                'type' => 'unit_tribe',
                'description' => 'Gallic civilization units',
                'parent_id' => NULL,
                'sort_order' => 3,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'meta' => '{"icon":"bow","color":"#7c3aed","order":3,"specialty":"defense"}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 20,
                'name' => 'Egyptians',
                'slug' => 'egyptians',
                'type' => 'unit_tribe',
                'description' => 'Egyptian civilization units',
                'parent_id' => NULL,
                'sort_order' => 4,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'meta' => '{"icon":"pyramid","color":"#d97706","order":4,"specialty":"archers"}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 21,
                'name' => 'Huns',
                'slug' => 'huns',
                'type' => 'unit_tribe',
                'description' => 'Hunnic civilization units',
                'parent_id' => NULL,
                'sort_order' => 5,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'meta' => '{"icon":"horse","color":"#be185d","order":5,"specialty":"cavalry"}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 22,
                'name' => 'Military Technology',
                'slug' => 'military',
                'type' => 'technology_category',
                'description' => 'Technologies for military advancement',
                'parent_id' => NULL,
                'sort_order' => 1,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'meta' => '{"icon":"sword","color":"#ef4444","order":1}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 23,
                'name' => 'Economic Technology',
                'slug' => 'economy',
                'type' => 'technology_category',
                'description' => 'Technologies for economic development',
                'parent_id' => NULL,
                'sort_order' => 2,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'meta' => '{"icon":"coins","color":"#f59e0b","order":2}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 24,
                'name' => 'Infrastructure Technology',
                'slug' => 'infrastructure',
                'type' => 'technology_category',
                'description' => 'Technologies for infrastructure improvement',
                'parent_id' => NULL,
                'sort_order' => 3,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'meta' => '{"icon":"building","color":"#6b7280","order":3}',
                'created_at' => '2025-09-27 00:38:53',
                'updated_at' => '2025-09-27 00:38:53',
                'deleted_at' => NULL,
            ],
            [
                'id' => 25,
                'name' => 'Research Technology',
                'slug' => 'research',
                'type' => 'technology_category',
                'description' => 'Technologies for research and development',
                'parent_id' => NULL,
                'sort_order' => 4,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'meta' => '{"icon":"flask","color":"#3b82f6","order":4}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 26,
                'name' => 'Special Technology',
                'slug' => 'special',
                'type' => 'technology_category',
                'description' => 'Unique and special technologies',
                'parent_id' => NULL,
                'sort_order' => 5,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'meta' => '{"icon":"sparkles","color":"#8b5cf6","order":5}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 27,
                'name' => 'Wood',
                'slug' => 'wood',
                'type' => 'resource_type',
                'description' => 'Basic building material',
                'parent_id' => NULL,
                'sort_order' => 1,
                'lft' => 1,
                'rgt' => 2,
                'depth' => 0,
                'meta' => '{"icon":"tree","color":"#8b4513","order":1}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 28,
                'name' => 'Clay',
                'slug' => 'clay',
                'type' => 'resource_type',
                'description' => 'Construction material',
                'parent_id' => NULL,
                'sort_order' => 2,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 0,
                'meta' => '{"icon":"brick","color":"#cd853f","order":2}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 29,
                'name' => 'Iron',
                'slug' => 'iron',
                'type' => 'resource_type',
                'description' => 'Metal for weapons and tools',
                'parent_id' => NULL,
                'sort_order' => 3,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 0,
                'meta' => '{"icon":"hammer","color":"#708090","order":3}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 30,
                'name' => 'Crop',
                'slug' => 'crop',
                'type' => 'resource_type',
                'description' => 'Food for population',
                'parent_id' => NULL,
                'sort_order' => 4,
                'lft' => 7,
                'rgt' => 8,
                'depth' => 0,
                'meta' => '{"icon":"wheat","color":"#9acd32","order":4}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ],
            [
                'id' => 31,
                'name' => 'Gold',
                'slug' => 'gold',
                'type' => 'resource_type',
                'description' => 'Premium currency',
                'parent_id' => NULL,
                'sort_order' => 5,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 0,
                'meta' => '{"icon":"coins","color":"#ffd700","order":5}',
                'created_at' => '2025-09-27 00:38:54',
                'updated_at' => '2025-09-27 00:38:54',
                'deleted_at' => NULL,
            ]
        ];
        
        DB::table("taxonomies")->insert($dataTables);
    }
}