<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --table-mode --all-tables
         *
         */

        $dataTables = [
            [
                'id' => 1,
                'name' => 'Legionnaire',
                'key' => 'legionnaire',
                'tribe' => 'roman',
                'description' => 'Roman infantry unit',
                'attack' => 40,
                'defense_infantry' => 35,
                'defense_cavalry' => 50,
                'speed' => 6,
                'carry_capacity' => 50,
                'costs' => '"{\\"wood\\":120,\\"clay\\":100,\\"iron\\":150,\\"crop\\":30}"',
                'requirements' => '"{\\"barracks\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 2,
                'name' => 'Praetorian',
                'key' => 'praetorian',
                'tribe' => 'roman',
                'description' => 'Roman defensive infantry',
                'attack' => 30,
                'defense_infantry' => 65,
                'defense_cavalry' => 35,
                'speed' => 5,
                'carry_capacity' => 20,
                'costs' => '"{\\"wood\\":100,\\"clay\\":130,\\"iron\\":55,\\"crop\\":100}"',
                'requirements' => '"{\\"barracks\\":1,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 3,
                'name' => 'Imperian',
                'key' => 'imperian',
                'tribe' => 'roman',
                'description' => 'Roman offensive infantry',
                'attack' => 70,
                'defense_infantry' => 40,
                'defense_cavalry' => 25,
                'speed' => 7,
                'carry_capacity' => 50,
                'costs' => '"{\\"wood\\":150,\\"clay\\":160,\\"iron\\":210,\\"crop\\":80}"',
                'requirements' => '"{\\"barracks\\":5,\\"smithy\\":2}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 4,
                'name' => 'Equites Legati',
                'key' => 'equites_legati',
                'tribe' => 'roman',
                'description' => 'Roman scout cavalry',
                'attack' => 0,
                'defense_infantry' => 20,
                'defense_cavalry' => 10,
                'speed' => 16,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":140,\\"clay\\":160,\\"iron\\":20,\\"crop\\":40}"',
                'requirements' => '"{\\"stable\\":1,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 5,
                'name' => 'Equites Imperatoris',
                'key' => 'equites_imperatoris',
                'tribe' => 'roman',
                'description' => 'Roman heavy cavalry',
                'attack' => 120,
                'defense_infantry' => 65,
                'defense_cavalry' => 50,
                'speed' => 14,
                'carry_capacity' => 100,
                'costs' => '"{\\"wood\\":550,\\"clay\\":440,\\"iron\\":320,\\"crop\\":100}"',
                'requirements' => '"{\\"stable\\":5,\\"smithy\\":3}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 6,
                'name' => 'Equites Caesaris',
                'key' => 'equites_caesaris',
                'tribe' => 'roman',
                'description' => 'Roman elite cavalry',
                'attack' => 180,
                'defense_infantry' => 80,
                'defense_cavalry' => 105,
                'speed' => 10,
                'carry_capacity' => 70,
                'costs' => '"{\\"wood\\":550,\\"clay\\":640,\\"iron\\":800,\\"crop\\":180}"',
                'requirements' => '"{\\"stable\\":10,\\"smithy\\":5}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 7,
                'name' => 'Clubswinger',
                'key' => 'clubswinger',
                'tribe' => 'teuton',
                'description' => 'Teuton infantry unit',
                'attack' => 40,
                'defense_infantry' => 20,
                'defense_cavalry' => 5,
                'speed' => 7,
                'carry_capacity' => 60,
                'costs' => '"{\\"wood\\":95,\\"clay\\":75,\\"iron\\":40,\\"crop\\":40}"',
                'requirements' => '"{\\"barracks\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 8,
                'name' => 'Spearman',
                'key' => 'spearman',
                'tribe' => 'teuton',
                'description' => 'Teuton defensive infantry',
                'attack' => 10,
                'defense_infantry' => 35,
                'defense_cavalry' => 60,
                'speed' => 7,
                'carry_capacity' => 40,
                'costs' => '"{\\"wood\\":145,\\"clay\\":70,\\"iron\\":85,\\"crop\\":40}"',
                'requirements' => '"{\\"barracks\\":1,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 9,
                'name' => 'Axeman',
                'key' => 'axeman',
                'tribe' => 'teuton',
                'description' => 'Teuton offensive infantry',
                'attack' => 60,
                'defense_infantry' => 30,
                'defense_cavalry' => 30,
                'speed' => 6,
                'carry_capacity' => 50,
                'costs' => '"{\\"wood\\":130,\\"clay\\":120,\\"iron\\":170,\\"crop\\":70}"',
                'requirements' => '"{\\"barracks\\":3,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 10,
                'name' => 'Scout',
                'key' => 'scout',
                'tribe' => 'teuton',
                'description' => 'Teuton scout cavalry',
                'attack' => 0,
                'defense_infantry' => 10,
                'defense_cavalry' => 5,
                'speed' => 9,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":160,\\"clay\\":100,\\"iron\\":50,\\"crop\\":50}"',
                'requirements' => '"{\\"stable\\":1,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 11,
                'name' => 'Paladin',
                'key' => 'paladin',
                'tribe' => 'teuton',
                'description' => 'Teuton heavy cavalry',
                'attack' => 55,
                'defense_infantry' => 100,
                'defense_cavalry' => 40,
                'speed' => 10,
                'carry_capacity' => 110,
                'costs' => '"{\\"wood\\":370,\\"clay\\":270,\\"iron\\":290,\\"crop\\":75}"',
                'requirements' => '"{\\"stable\\":3,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 12,
                'name' => 'Teutonic Knight',
                'key' => 'teutonic_knight',
                'tribe' => 'teuton',
                'description' => 'Teuton elite cavalry',
                'attack' => 150,
                'defense_infantry' => 50,
                'defense_cavalry' => 75,
                'speed' => 9,
                'carry_capacity' => 80,
                'costs' => '"{\\"wood\\":450,\\"clay\\":515,\\"iron\\":480,\\"crop\\":80}"',
                'requirements' => '"{\\"stable\\":5,\\"smithy\\":3}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 13,
                'name' => 'Phalanx',
                'key' => 'phalanx',
                'tribe' => 'gaul',
                'description' => 'Gaul infantry unit',
                'attack' => 15,
                'defense_infantry' => 40,
                'defense_cavalry' => 50,
                'speed' => 7,
                'carry_capacity' => 35,
                'costs' => '"{\\"wood\\":100,\\"clay\\":130,\\"iron\\":55,\\"crop\\":30}"',
                'requirements' => '"{\\"barracks\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 14,
                'name' => 'Swordsman',
                'key' => 'swordsman',
                'tribe' => 'gaul',
                'description' => 'Gaul offensive infantry',
                'attack' => 65,
                'defense_infantry' => 35,
                'defense_cavalry' => 20,
                'speed' => 6,
                'carry_capacity' => 45,
                'costs' => '"{\\"wood\\":140,\\"clay\\":150,\\"iron\\":185,\\"crop\\":60}"',
                'requirements' => '"{\\"barracks\\":3,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 15,
                'name' => 'Pathfinder',
                'key' => 'pathfinder',
                'tribe' => 'gaul',
                'description' => 'Gaul scout cavalry',
                'attack' => 0,
                'defense_infantry' => 20,
                'defense_cavalry' => 10,
                'speed' => 17,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":170,\\"clay\\":150,\\"iron\\":20,\\"crop\\":40}"',
                'requirements' => '"{\\"stable\\":1,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 16,
                'name' => 'Theutates Thunder',
                'key' => 'theutates_thunder',
                'tribe' => 'gaul',
                'description' => 'Gaul heavy cavalry',
                'attack' => 90,
                'defense_infantry' => 25,
                'defense_cavalry' => 40,
                'speed' => 19,
                'carry_capacity' => 75,
                'costs' => '"{\\"wood\\":350,\\"clay\\":450,\\"iron\\":230,\\"crop\\":60}"',
                'requirements' => '"{\\"stable\\":3,\\"smithy\\":1}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 17,
                'name' => 'Druidrider',
                'key' => 'druidrider',
                'tribe' => 'gaul',
                'description' => 'Gaul elite cavalry',
                'attack' => 45,
                'defense_infantry' => 115,
                'defense_cavalry' => 55,
                'speed' => 16,
                'carry_capacity' => 35,
                'costs' => '"{\\"wood\\":360,\\"clay\\":330,\\"iron\\":280,\\"crop\\":120}"',
                'requirements' => '"{\\"stable\\":5,\\"smithy\\":3}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 18,
                'name' => 'Haeduan',
                'key' => 'haeduan',
                'tribe' => 'gaul',
                'description' => 'Gaul elite cavalry',
                'attack' => 140,
                'defense_infantry' => 60,
                'defense_cavalry' => 165,
                'speed' => 16,
                'carry_capacity' => 65,
                'costs' => '"{\\"wood\\":500,\\"clay\\":620,\\"iron\\":675,\\"crop\\":170}"',
                'requirements' => '"{\\"stable\\":10,\\"smithy\\":5}"',
                'is_special' => 0,
                'is_active' => 1,
                'created_at' => '2025-09-25 23:37:48',
                'updated_at' => '2025-09-25 23:37:48',
            ],
            [
                'id' => 19,
                'name' => 'Ram',
                'key' => 'ram',
                'tribe' => 'roman',
                'description' => 'Roman siege weapon for destroying walls',
                'attack' => 2,
                'defense_infantry' => 20,
                'defense_cavalry' => 50,
                'speed' => 4,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":300,\\"clay\\":200,\\"iron\\":200,\\"crop\\":100}"',
                'requirements' => '"{\\"workshop\\":1}"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 20,
                'name' => 'Catapult',
                'key' => 'catapult',
                'tribe' => 'roman',
                'description' => 'Roman siege weapon for destroying buildings',
                'attack' => 100,
                'defense_infantry' => 100,
                'defense_cavalry' => 50,
                'speed' => 3,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":320,\\"clay\\":400,\\"iron\\":100,\\"crop\\":100}"',
                'requirements' => '"{\\"workshop\\":1}"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 21,
                'name' => 'Ram',
                'key' => 'ram',
                'tribe' => 'teuton',
                'description' => 'Teuton siege weapon for destroying walls',
                'attack' => 2,
                'defense_infantry' => 20,
                'defense_cavalry' => 50,
                'speed' => 4,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":300,\\"clay\\":200,\\"iron\\":200,\\"crop\\":100}"',
                'requirements' => '"{\\"workshop\\":1}"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 22,
                'name' => 'Catapult',
                'key' => 'catapult',
                'tribe' => 'teuton',
                'description' => 'Teuton siege weapon for destroying buildings',
                'attack' => 100,
                'defense_infantry' => 100,
                'defense_cavalry' => 50,
                'speed' => 3,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":320,\\"clay\\":400,\\"iron\\":100,\\"crop\\":100}"',
                'requirements' => '"{\\"workshop\\":1}"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 23,
                'name' => 'Ram',
                'key' => 'ram',
                'tribe' => 'gaul',
                'description' => 'Gaul siege weapon for destroying walls',
                'attack' => 2,
                'defense_infantry' => 20,
                'defense_cavalry' => 50,
                'speed' => 4,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":300,\\"clay\\":200,\\"iron\\":200,\\"crop\\":100}"',
                'requirements' => '"{\\"workshop\\":1}"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 24,
                'name' => 'Catapult',
                'key' => 'catapult',
                'tribe' => 'gaul',
                'description' => 'Gaul siege weapon for destroying buildings',
                'attack' => 100,
                'defense_infantry' => 100,
                'defense_cavalry' => 50,
                'speed' => 3,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":320,\\"clay\\":400,\\"iron\\":100,\\"crop\\":100}"',
                'requirements' => '"{\\"workshop\\":1}"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 25,
                'name' => 'Natarian Soldier',
                'key' => 'natarian_soldier',
                'tribe' => 'natars',
                'description' => 'Natarian defensive unit',
                'attack' => 40,
                'defense_infantry' => 60,
                'defense_cavalry' => 40,
                'speed' => 5,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":0,\\"clay\\":0,\\"iron\\":0,\\"crop\\":0}"',
                'requirements' => '"[]"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 26,
                'name' => 'Natarian Archer',
                'key' => 'natarian_archer',
                'tribe' => 'natars',
                'description' => 'Natarian ranged unit',
                'attack' => 60,
                'defense_infantry' => 30,
                'defense_cavalry' => 30,
                'speed' => 6,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":0,\\"clay\\":0,\\"iron\\":0,\\"crop\\":0}"',
                'requirements' => '"[]"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ],
            [
                'id' => 27,
                'name' => 'Natarian Knight',
                'key' => 'natarian_knight',
                'tribe' => 'natars',
                'description' => 'Natarian elite cavalry',
                'attack' => 120,
                'defense_infantry' => 50,
                'defense_cavalry' => 80,
                'speed' => 8,
                'carry_capacity' => 0,
                'costs' => '"{\\"wood\\":0,\\"clay\\":0,\\"iron\\":0,\\"crop\\":0}"',
                'requirements' => '"[]"',
                'is_special' => 1,
                'is_active' => 1,
                'created_at' => '2025-09-27 00:32:47',
                'updated_at' => '2025-09-27 00:32:47',
            ]
        ];
        
        foreach ($dataTables as $data) {
            DB::table("unit_types")->updateOrInsert(['id' => $data['id']], $data);
        }
    }
}